---
abstract: 'Simple class to manage a Nginx server'
author:
  - 'Chris Prather <chris@prather.org$<gt>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  Test::TempDir: 0
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nginx-Control
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.32
  MooseX::Types::Path::Class: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
